#publish your docker image to github container registry
name: publish

on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.pword }}

      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/radha3885/:latest
          docker run ghcr.io/radha3885/dicker-image-build:latest
          docker push ghcr.io/radha3885/docker-image-build:latest
